include: package:lint/analysis_options.yaml

linter:
  rules:

    # Use parameter order as in json response
    always_put_required_named_parameters_first: true
    
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false


    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    
    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true

    # Remove when the app is ready for production
    avoid_print: false
