name: kuharko
description: Flutter application for checking out cool recipes

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  flutter_spinkit: ^5.0.0
  get: ^4.0.0-nullsafety.2
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.2
  audioplayers: ^0.18.0
  shimmer: ^2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.4+1
  lint: ^1.5.3

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#212430'
  adaptive_icon_foreground: 'assets/icon.png'

flutter_native_splash:
  android: true
  ios: true
  color: '#ffffff'
  image: 'assets/icon.png'
  image_dark: 'assets/icon.png'
  color_dark: '#212430'

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/bottom/
    - assets/icons/categories/
    - assets/icons/illustrations/
    - assets/icons/home_recipe/
    - assets/icons/recipe/
    - assets/icons/results/
    - assets/icons/search/
    - assets/images/
    - assets/boom.wav

  fonts:
    - family: VisbyRound
      fonts:
        - asset: assets/fonts/VisbyRound/VisbyRound-Regular.ttf
        - asset: assets/fonts/VisbyRound/VisbyRound-Medium.ttf
          weight: 500
        - asset: assets/fonts/VisbyRound/VisbyRound-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/VisbyRound/VisbyRound-Bold.ttf
          weight: 700
        - asset: assets/fonts/VisbyRound/VisbyRound-ExtraBold.ttf
          weight: 800
