name: receptko
description: Flutter application for checking out cool recipes

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  flutter_spinkit: ^4.1.2+1
  get: ^3.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/bottom/
    - assets/icons/categories/
    - assets/icons/home_recipe/
    - assets/icons/recipe/
    - assets/icons/results/
    - assets/images/

  fonts:
    - family: VisbyRound
      fonts:
        - asset: assets/fonts/VisbyRound/VisbyRound-Regular.ttf
        - asset: assets/fonts/VisbyRound/VisbyRound-Medium.ttf
          weight: 500
        - asset: assets/fonts/VisbyRound/VisbyRound-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/VisbyRound/VisbyRound-Bold.ttf
          weight: 700
        - asset: assets/fonts/VisbyRound/VisbyRound-ExtraBold.ttf
          weight: 800
